# Generated by Django 3.0.6 on 2020-05-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='picture',
        ),
        migrations.AddField(
            model_name='character',
            name='image',
            field=models.ImageField(default=0, upload_to='users/pictures/', verbose_name='foto de perfil'),
            preserve_default=False,
        ),
    ]
